= Quarkus RabbitMQ Client
:extension-status: preview

include::./includes/attributes.adoc[]

RabbitMQ is a popular message broker. This Quarkus extension provides a client for RabbitMQ which is configurable using the `application.properties`.

== Installation

If you want to use this extension, you need to add the `quarkus-rabbitmq-client` extension first.
In your `pom.xml` file, add:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.rabbitmqclient</groupId>
    <artifactId>quarkus-rabbitmq-client</artifactId>
    <version>{quarkus-rabbitmq-client-version}</version>
</dependency>
----

== Usage
Assuming you have RabbitMQ running on localhost:5672 you should add the following properties to your `application.properties` and fill in the values for `<username>` and `<password>`.

[source,properties]
----
quarkus.rabbitmqclient.virtual-host=/
quarkus.rabbitmqclient.username=<username>
quarkus.rabbitmqclient.password=<password>
quarkus.rabbitmqclient.hostname=localhost
quarkus.rabbitmqclient.port=5672
----

Once you have configured the properties, you can start using the RabbitMQ client.

[source,java]
----
package org.acme.rabbitmqclient;

include::{examples-dir}/MessageService.java[tag=skeleton,indent=0,tabsize=2]
----

You do not need to worry about closing connections as the `RabbitMQClient` will close them for you on application shutdown.

=== Multiple RabbitMQ Clients
The extension supports having multiple RabbitMQ clients. You can add named RabbitMQ clients as follows.

```properties
quarkus.rabbitmqclient.<name>.virtual-host=/
quarkus.rabbitmqclient.<name>.username=<username>
quarkus.rabbitmqclient.<name>.password=<password>
quarkus.rabbitmqclient.<name>.hostname=localhost
quarkus.rabbitmqclient.<name>.port=5672
```
All configuration options that are available on the default non named RabbitMQ client are available. Injecting a named RabbitMQ client, e.g. foo, can be achieved as follows.

```java
@ApplicationScoped
public class MessageService {

    @Inject
    @NamedRabbitMQClient("foo")
    RabbitMQClient fooClient;
}
```

It is possible to use multiple RabbitMQ clients in the same class as long as they are all named, or in combination with the default client. The name `default` is reserved for the default client and if used will trigger a deployment exception.

=== Credentials Provider
The extension supports retrieve login/password from Credentials Provider(io.quarkus.credentials.CredentialsProvider) for example Hashicorp Vault.
Credentials Provider should be present and configured.
```properties
quarkus.rabbitmqclient.<name>.virtual-host=/
quarkus.rabbitmqclient.<name>.hostname=localhost
quarkus.rabbitmqclient.<name>.port=5672
quarkus.rabbitmqclient.credentials-provider=custom
```
The property `quarkus.rabbitmqclient.credentials-provider` should contain identifier by which credential provider return login/password.

In case the multiple credentials providers exist
For Vault, the credentials provider bean name is vault-credentials-provider from extension https://docs.quarkiverse.io/quarkus-vault/dev/index.html
Or use annotation @Named("custom-provider-name").

```properties
quarkus.rabbitmqclient.<name>.virtual-host=/
quarkus.rabbitmqclient.<name>.hostname=localhost
quarkus.rabbitmqclient.<name>.port=5672
quarkus.rabbitmqclient.credentials-provider=custom
quarkus.rabbitmqclient.credentials-provider-name=vault-credentials-provider
```
CAUTION: Login/password can overwrite settings from properties.

If credential is renewable and has "expires-at" will be create `com.rabbitmq.client.impl.DefaultCredentialsRefreshService`

=== Disabling Clients
It is possible to disable clients using the `quarkus.rabbitmqclient.<client-nane>.enabled=false` configuration property. To disable the default client, use `quarkus.rabbitmqclient.enabled=false`.

== Metrics
Both Micrometer and SmallRye Metrics are supported and enabled by default if the `quarkus-micrometer` or `quarkus-smallrye-metrics` dependency is included in the project. If both are present micrometer will be used.

Metrics are gathered on a per-client basis and tagged with `name=<client-name>` of the client. The default clients is tagged with `name=default` and are all prefixed with `rabbitmq`.

It is possible to opt-out of metrics by specifying `quarkus.rabbitmqclient.metrics.enabled=false`. This will disable all metrics gathering.

[[configuration-reference]]
== Configuration Reference

include::includes/quarkus-rabbitmqclient.adoc[leveloffset=+1, opts=optional]
