quarkus.log.level=INFO

quarkus.rabbitmqclient.health.enabled=true
quarkus.rabbitmqclient.metrics.enabled=false

# default client non-ssl
quarkus.rabbitmqclient.username=${test.username:guest}
quarkus.rabbitmqclient.password=${test.password:guest}
quarkus.rabbitmqclient.hostname=${test.hostname:localhost}
quarkus.rabbitmqclient.port=${test.amqp-port:5672}